import KingDiamonds from "@/assets/King of diamonds2.svg";
import AceDiamonds from "@/assets/Ace of diamonds.svg";
import QueenDiamonds from "@/assets/Queen of diamonds2.svg";
import JackDiamonds from "@/assets/Jack of diamonds2.svg";
import TwoDiamonds from "@/assets/2 of diamonds.svg";
import ThreeDiamonds from "@/assets/3 of diamonds.svg";
import FourDiamonds from "@/assets/4 of diamonds.svg";
import FiveDiamonds from "@/assets/5 of diamonds.svg";
import SixDiamonds from "@/assets/6 of diamonds.svg";
import SevenDiamonds from "@/assets/7 of diamonds.svg";
import EightDiamonds from "@/assets/8 of diamonds.svg";
import NineDiamonds from "@/assets/9 of diamonds.svg";
import TenDiamonds from "@/assets/10 of diamonds.svg";
import KingClubs from "@/assets/King of clubs2.svg";
import AceClubs from "@/assets/Ace of clubs.svg";
import QueenClubs from "@/assets/Queen of clubs2.svg";
import JackClubs from "@/assets/Jack of clubs2.svg";
import TwoClubs from "@/assets/2 of clubs.svg";
import ThreeClubs from "@/assets/3 of clubs.svg";
import FourClubs from "@/assets/4 of clubs.svg";
import FiveClubs from "@/assets/5 of clubs.svg";
import SixClubs from "@/assets/6 of clubs.svg";
import SevenClubs from "@/assets/7 of clubs.svg";
import EightClubs from "@/assets/8 of clubs.svg";
import NineClubs from "@/assets/9 of clubs.svg";
import TenClubs from "@/assets/10 of clubs.svg";
import KingSpades from "@/assets/King of spades2.svg";
import AceSpades from "@/assets/Ace of spades.svg";
import QueenSpades from "@/assets/Queen of spades2.svg";
import JackSpades from "@/assets/Jack of spades2.svg";
import TwoSpades from "@/assets/2 of spades.svg";
import ThreeSpades from "@/assets/3 of spades.svg";
import FourSpades from "@/assets/4 of spades.svg";
import FiveSpades from "@/assets/5 of spades.svg";
import SixSpades from "@/assets/6 of spades.svg";
import SevenSpades from "@/assets/7 of spades.svg";
import EightSpades from "@/assets/8 of spades.svg";
import NineSpades from "@/assets/9 of spades.svg";
import TenSpades from "@/assets/10 of spades.svg";
import KingHearts from "@/assets/King of hearts2.svg";
import AceHearts from "@/assets/Ace of hearts.svg";
import QueenHearts from "@/assets/Queen of hearts2.svg";
import JackHearts from "@/assets/Jack of hearts2.svg";
import TwoHearts from "@/assets/2 of hearts.svg";
import ThreeHearts from "@/assets/3 of hearts.svg";
import FourHearts from "@/assets/4 of hearts.svg";
import FiveHearts from "@/assets/5 of hearts.svg";
import SixHearts from "@/assets/6 of hearts.svg";
import SevenHearts from "@/assets/7 of hearts.svg";
import EightHearts from "@/assets/8 of hearts.svg";
import NineHearts from "@/assets/9 of hearts.svg";
import TenHearts from "@/assets/10 of hearts.svg";
import type { PlayingCard } from "@/types/CardTypes";

export default function loadCard(card: PlayingCard) {
  if (card.suit == "Diamonds" && card.name == "King") return KingDiamonds;
  if (card.suit == "Diamonds" && card.name == "Ace") return AceDiamonds;
  if (card.suit == "Diamonds" && card.name == "Queen") return QueenDiamonds;
  if (card.suit == "Diamonds" && card.name == "Jack") return JackDiamonds;
  if (card.suit == "Diamonds" && card.name == 2) return TwoDiamonds;
  if (card.suit == "Diamonds" && card.name == 3) return ThreeDiamonds;
  if (card.suit == "Diamonds" && card.name == 4) return FourDiamonds;
  if (card.suit == "Diamonds" && card.name == 5) return FiveDiamonds;
  if (card.suit == "Diamonds" && card.name == 6) return SixDiamonds;
  if (card.suit == "Diamonds" && card.name == 7) return SevenDiamonds;
  if (card.suit == "Diamonds" && card.name == 8) return EightDiamonds;
  if (card.suit == "Diamonds" && card.name == 9) return NineDiamonds;
  if (card.suit == "Diamonds" && card.name == 10) return TenDiamonds;
  if (card.suit == "Clubs" && card.name == "King") return KingClubs;
  if (card.suit == "Clubs" && card.name == "Ace") return AceClubs;
  if (card.suit == "Clubs" && card.name == "Queen") return QueenClubs;
  if (card.suit == "Clubs" && card.name == "Jack") return JackClubs;
  if (card.suit == "Clubs" && card.name == 2) return TwoClubs;
  if (card.suit == "Clubs" && card.name == 3) return ThreeClubs;
  if (card.suit == "Clubs" && card.name == 4) return FourClubs;
  if (card.suit == "Clubs" && card.name == 5) return FiveClubs;
  if (card.suit == "Clubs" && card.name == 6) return SixClubs;
  if (card.suit == "Clubs" && card.name == 7) return SevenClubs;
  if (card.suit == "Clubs" && card.name == 8) return EightClubs;
  if (card.suit == "Clubs" && card.name == 9) return NineClubs;
  if (card.suit == "Clubs" && card.name == 10) return TenClubs;  
  if (card.suit == "Spades" && card.name == "King") return KingSpades;
  if (card.suit == "Spades" && card.name == "Ace") return AceSpades;
  if (card.suit == "Spades" && card.name == "Queen") return QueenSpades;
  if (card.suit == "Spades" && card.name == "Jack") return JackSpades;
  if (card.suit == "Spades" && card.name == 2) return TwoSpades;
  if (card.suit == "Spades" && card.name == 3) return ThreeSpades;
  if (card.suit == "Spades" && card.name == 4) return FourSpades;
  if (card.suit == "Spades" && card.name == 5) return FiveSpades;
  if (card.suit == "Spades" && card.name == 6) return SixSpades;
  if (card.suit == "Spades" && card.name == 7) return SevenSpades;
  if (card.suit == "Spades" && card.name == 8) return EightSpades;
  if (card.suit == "Spades" && card.name == 9) return NineSpades;
  if (card.suit == "Spades" && card.name == 10) return TenSpades;
  if (card.suit == "Hearts" && card.name == "King") return KingHearts;
  if (card.suit == "Hearts" && card.name == "Ace") return AceHearts;
  if (card.suit == "Hearts" && card.name == "Queen") return QueenHearts;
  if (card.suit == "Hearts" && card.name == "Jack") return JackHearts;
  if (card.suit == "Hearts" && card.name == 2) return TwoHearts;
  if (card.suit == "Hearts" && card.name == 3) return ThreeHearts;
  if (card.suit == "Hearts" && card.name == 4) return FourHearts;
  if (card.suit == "Hearts" && card.name == 5) return FiveHearts;
  if (card.suit == "Hearts" && card.name == 6) return SixHearts;
  if (card.suit == "Hearts" && card.name == 7) return SevenHearts;
  if (card.suit == "Hearts" && card.name == 8) return EightHearts;
  if (card.suit == "Hearts" && card.name == 9) return NineHearts;
  if (card.suit == "Hearts" && card.name == 10) return TenHearts;
};
